# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
#
# While our "example" application has the platform-specific code,
# for simplicity we are compiling and testing everything on the Ubuntu environment only.
# For multi-OS testing see the `cross.yml` workflow.

on: [workflow_call]

name: Python Integration

jobs:
  install-python:
    name: Install
    runs-on: ubuntu-latest
    inputs:
      python-version:
        required: true
        type: string

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: actions/checkout@v4
      - name: Set up Python ${{ python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ python-version }}

      - name: create virtual environment
        run: |
          pip install --upgrade pip
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      
      - name: install cellular_raza
        run: |
          pip install .

