name: Create Docs

on: [push]

jobs:
  build-docs:
    name: Build Docs
    runs-on: ubuntu-latest

    steps:
      - name: Configure Python environment
        uses: ./.github/workflows/python_integration.yml

      - name: Install Doc Requirements
        run: |
          pip install -r docs/requirements.txt

      - name: Install latex
        run: |
          python -m pip install latex
          sudo apt install texlive texlive-latex-extra texlive-fonts-recommended dvipng cm-super

      - name: Generate Plots for Documentation
        run: |
          python docs/create_plots.py

      - name: Sphinx build
        run: |
          sphinx-build docs/source docs/build/html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html/
          force_orphan: true
